[package]
name = "guessing_game"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
chrono = "0.4"
colored = "2.0"
mysql_async = "0.33"
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"
